"""index evaluations policy_set_id and timestamp

Revision ID: 222abe350967
Revises: b2c3d4e5f6a7
Create Date: 2026-08-08 10:29:37.417338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222abe350967'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_evaluations_policy_set_timestamp', 'evaluations', ['policy_set_id', 'evaluation_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evaluations_policy_set_timestamp', table_name='evaluations')
    # ### end Alembic commands ###
