"""initial schema

Revision ID: 462629343c67
Revises: 
Create Date: 2026-08-07 15:10:50.491065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '462629343c67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('entity_type', sa.String(length=150), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_messages',
    sa.Column('message_type', sa.String(length=150), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_authorities',
    sa.Column('level', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', 'owner', name='uq_policy_authorities_level_owner')
    )
    op.create_table('policy_sets',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('source_documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_system', sa.String(length=200), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approved_policy_versions',
    sa.Column('policy_set_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=200), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_set_id'], ['policy_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_set_id', 'version_number', name='uq_approved_policy_versions_set_version')
    )
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'content_hash', name='uq_document_versions_doc_hash')
    )
    op.create_table('approved_rules',
    sa.Column('policy_version_id', sa.UUID(), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=200), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('machine_executable', sa.Boolean(), nullable=False),
    sa.Column('ambiguity_status', sa.String(length=50), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('scope_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('condition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effect_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_facts_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lineage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['policy_authorities.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['approved_policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_version_id', 'rule_id', 'revision', name='uq_approved_rules_version_rule_revision')
    )
    op.create_table('clauses',
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('clause_ref', sa.String(length=200), nullable=False),
    sa.Column('section', sa.String(length=300), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('policy_set_id', sa.UUID(), nullable=False),
    sa.Column('policy_version_id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.String(length=200), nullable=True),
    sa.Column('calling_system_identity', sa.String(length=200), nullable=True),
    sa.Column('request_facts_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_status', sa.String(length=50), nullable=False),
    sa.Column('result_hash', sa.String(length=128), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_set_id'], ['policy_sets.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['approved_policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction_runs',
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('deployment_name', sa.String(length=200), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_rules',
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('policy_set_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ),
    sa.ForeignKeyConstraint(['policy_set_id'], ['policy_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_references',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('clause_id', sa.UUID(), nullable=True),
    sa.Column('source_hash', sa.String(length=128), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=300), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['approved_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_exceptions',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('exception_key', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('condition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effect_override_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['approved_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_exceptions')
    op.drop_table('evidence_references')
    op.drop_table('candidate_rules')
    op.drop_table('extraction_runs')
    op.drop_table('evaluations')
    op.drop_table('clauses')
    op.drop_table('approved_rules')
    op.drop_table('document_versions')
    op.drop_table('approved_policy_versions')
    op.drop_table('source_documents')
    op.drop_table('policy_sets')
    op.drop_table('policy_authorities')
    op.drop_table('outbox_messages')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
