"""candidate rule review audit columns

Revision ID: 4a5e7f5efae5
Revises: 462629343c67
Create Date: 2026-08-07 15:46:06.531413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5e7f5efae5'
down_revision: Union[str, Sequence[str], None] = '462629343c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_rules', sa.Column('reviewed_by', sa.String(length=200), nullable=True))
    op.add_column('candidate_rules', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candidate_rules', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('candidate_rules', sa.Column('published_version_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'candidate_rules', 'approved_policy_versions', ['published_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate_rules', type_='foreignkey')
    op.drop_column('candidate_rules', 'published_version_id')
    op.drop_column('candidate_rules', 'review_notes')
    op.drop_column('candidate_rules', 'reviewed_at')
    op.drop_column('candidate_rules', 'reviewed_by')
    # ### end Alembic commands ###
