"""Deciding what an extraction run actually changed.

Re-extracting a document is cheap; re-reviewing it is not. Before this module,
a second run of the same document produced a full set of candidate rules that
looked entirely new, so a reviewer who had already worked through 52 rules was
handed 52 rules again with no way to tell which two of them were the point.

This module answers one question: *for each rule this run produced, had we
already seen it?* It is deliberately pure — no database, no session, no I/O — so
the matching rules can be reasoned about and tested directly, and so the same
comparison works for two runs of one document version and for a run against the
previous *variant* of the same document.

## What counts as "the same rule"

Nothing generated by the language model is stable enough to be an identity.
`rule_id` is a fresh `AI-<random>` per rule, `effective_from` is
`date.today()`, and the prose is regenerated from scratch on every run. Matching
on any of those would report the entire document as changed every time.

So identity is built from what a rule *does* and what it *came from*:

- **content fingerprint** — everything the record says about what it decides.
  Built by *removing* what is not meaning rather than by listing what is. The
  first version of this listed ten fields and, by omission, excluded the
  canonical rule core — the subject, predicate, trigger, deadline and temporal
  constraint that say what the rule actually decides. Seven of its ten fields
  turned out to be constant across the entire corpus, so the identity reduced in
  practice to rule type plus effect, and three pairs of genuinely different
  rules in one live run hashed the same. An identity that omits the thing being
  identified is wrong eventually by construction.

  Removing rather than listing also fails in the safe direction. A field nobody
  has classified is included, so at worst two rules look different and a
  reviewer is asked a question they did not need to be asked. The other way
  round, a field nobody has classified is ignored, and a reviewer's approval is
  carried onto a rule they never read.
- **anchor fingerprint** — the verbatim source passage the rule was formulated
  from (`formulation.source_text`, which the contract already calls "the anchor
  for the whole record"). This survives clause renumbering, which matters
  because a new document variant reflows clause refs even where the words are
  untouched.
- **prose fingerprint** — title and description. Deliberately *not* part of
  identity: the model rewords the same rule freely, and treating that as a
  change would bury the real ones. It is reported separately as `reworded` so a
  reviewer can still see it.

## The tiers

Matching runs in tiers, most-certain first, and each baseline rule can be
claimed only once — otherwise two new rules could both point at one old rule and
the "no longer extracted" set would silently under-report.

1. identical content, corroborated by the source passage -> `unchanged`
2. identical source passage, different semantics -> `changed` (the document did
   not move, so this is the extractor itself producing a different answer —
   worth showing precisely because it is not the document's doing)
3. similar source passage         -> `changed` (the document was revised)
4. nothing matched                -> `new`

Baseline rules left unclaimed are `removed`: the previous run found them and
this one did not. That is a signal in its own right — either the clause was
deleted from the new variant, or the extractor missed it.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Literal

from policy_platform.contracts.canonical import canonical_hash

#: Jaccard similarity over normalised word sets above which two source passages
#: are considered the same passage, revised. Chosen so that an edit to a clause
#: (a changed threshold, an added exception, a reworded sentence) still matches
#: its predecessor, while two genuinely different clauses about the same topic do
#: not. Below this, a rule is reported as `new` and its predecessor as `removed`,
#: which is the safe direction to fail: it asks for a fresh review rather than
#: quietly presenting an unrelated rule as an edit of another.
SIMILARITY_THRESHOLD = 0.6

DeltaStatus = Literal["baseline", "new", "changed", "unchanged"]

#: The ordered top-level fields the change explainer walks when showing a
#: reviewer *what* differs between two runs. This is a presentation ordering,
#: **not** the identity — `semantic_core` decides whether two rules are the same
#: rule, and it works by exclusion so that nothing can be forgotten out of it.
#: Kept separate deliberately: a list that drives a display can safely be
#: partial, and a list that drives an identity cannot.
SEMANTIC_FIELDS = (
    "rule_type",
    "scope",
    "condition",
    "effect",
    "priority",
    "exceptions",
    "required_facts",
    "advice",
    "is_explicit_override",
    "machine_executable",
)

#: Fields that say *when and how this row was made*, not what it decides. A rule
#: whose provenance differs is still the same rule.
NON_SEMANTIC_PROVENANCE = frozenset(
    {
        "rule_id",
        "lineage",
        "evidence",
        "effective_from",
        "effective_to",
        "policy_set_id",
        "policy_version_id",
        "rule_revision",
        "schema_version",
        "review_status",
    }
)

#: Fields computed after the fact, from other rules. Including them would make a
#: rule's identity depend on its neighbours, so adding one unrelated rule could
#: report an untouched rule as changed.
NON_SEMANTIC_DERIVED = frozenset(
    {"related_rule_ids", "candidate_relationships", "supersedes_rule_ids", "xacml_view"}
)

#: Wording and presentation. Excluded from content so that a reworded rule stays
#: `unchanged`; carried by `prose_fingerprint` instead and surfaced as
#: `reworded`, which is what lets a reviewer see a rewrite without being asked
#: to re-approve it.
NON_SEMANTIC_PROSE = frozenset({"title", "description", "category", "group_label"})

#: Positions in the model's own output array, at any depth. `source_index` is a
#: record's position among the canonical policies of one call; a DMN decision's
#: `source_rule_indexes` are its back-references to those positions. Two records
#: alike but for these are one record the model emitted twice, and a position is
#: not something a rule decides.
NON_SEMANTIC_POSITIONAL = frozenset({"source_index", "source_rule_indexes"})

#: The same three exclusions as above — provenance, derived-from-neighbours, and
#: prose — but for keys nested inside `formulation`, where the model's own
#: working is kept. Until this existed, only the *top level* was filtered, so a
#: rule could be reported `changed` because the model reworded a display string
#: several levels down while every decision it stated was identical. Measured on
#: two real re-extractions of unchanged documents, these recovered a tenth of the
#: rules that had been reported as changed.
#:
#: Every member is here for a stated reason, and each was measured on its own
#: before being added. This is a denylist, not a pattern: `semantic_core` works
#: by exclusion precisely so that a field nobody has classified yet still counts
#: towards identity (see `test_an_unclassified_field_is_included_rather_than_
#: ignored`), and a wildcard would quietly opt future fields out of that.
#:
#: What is deliberately *not* here matters as much. `attributes[].text` and
#: `fact_model[].name` read like prose but carry the decision — "5 days paid" is
#: the entitlement, not a description of it. Dropping a decision-bearing field
#: would let two rules that decide different things match, and a match copies the
#: reviewer's approval forward (see `_classify_run_delta`), so an over-broad
#: exclusion here forges a human's signature. Both were measured as worth nothing
#: anyway.
NON_SEMANTIC_NESTED = frozenset(
    {
        # A restatement of the canonical rule for display. The rule itself is
        # already in the core; including its projection asks the same question
        # twice and lets a rephrased projection outvote an identical decision.
        # The single largest contributor of the group.
        "semantic_projection",
        # The passage the rule was read from. `anchor_fingerprint` exists to
        # carry exactly this (see `_source_text`), so keeping it in the content
        # fingerprint too lets one fact decide identity twice — and makes a rule
        # whose passage was re-sliced by a whitespace look like a new decision.
        "source_text",
        # Which part of the passage a field was read from. Provenance, at the
        # granularity of a single field.
        "source_origin",
        # Cross-references to other rules in the same batch. Exactly the reason
        # `related_rule_ids` is in NON_SEMANTIC_DERIVED, one level down: a rule's
        # identity must not move because a neighbour appeared.
        "relationships",
        # The extractor's remarks on its own output — how confident it was, how
        # the projection went, what it noticed it lacked, where it saw more than
        # one reading. Notes about the reading, not the reading. `ambiguity_
        # status` remains a top-level field and is still part of identity.
        "extraction_status",
        "dmn_mapping_status",
        "missing_components",
        "ambiguity",
    }
)

NON_SEMANTIC: frozenset[str] = (
    NON_SEMANTIC_PROVENANCE | NON_SEMANTIC_DERIVED | NON_SEMANTIC_PROSE
)

#: Applied at every depth, unlike NON_SEMANTIC which applies only at the top.
NON_SEMANTIC_AT_ANY_DEPTH: frozenset[str] = NON_SEMANTIC_POSITIONAL | NON_SEMANTIC_NESTED


def _drop_nested(value):
    if isinstance(value, dict):
        return {
            key: _drop_nested(item)
            for key, item in value.items()
            if key not in NON_SEMANTIC_AT_ANY_DEPTH
        }
    if isinstance(value, list):
        return [_drop_nested(item) for item in value]
    return value


def semantic_core(payload: dict) -> dict:
    """What a rule decides, with provenance, prose and output positions removed.

    The single definition of record sameness in this system. Both cross-run
    delta matching and same-run consolidation ask the same question — *are these
    two the same rule?* — and if they answered it differently, one of them would
    eventually carry a decision the other would have refused to.

    Exclusion is deliberately shallow-by-default and deep only for the named
    keys in `NON_SEMANTIC_AT_ANY_DEPTH`. An unclassified field is *included*, so
    a new field nobody has thought about yet makes two rules look different —
    the safe direction, because the cost is a redundant review and the cost of
    the other direction is a decision carried onto a rule that changed.

    Callers that need the *whole* record, prose included, add the prose
    themselves rather than redefining the core.
    """
    return _drop_nested(
        {key: value for key, value in payload.items() if key not in NON_SEMANTIC}
    )


_WORD = re.compile(r"[^\W_]+", re.UNICODE)


def _normalise_words(text: str) -> list[str]:
    """Lowercased word tokens, punctuation and underscores dropped.

    Unicode-aware rather than ASCII: source documents here are not guaranteed to
    be English, and an ASCII-only tokeniser would reduce an Arabic passage to an
    empty set and match it against every other empty set.
    """
    return [m.group(0).lower() for m in _WORD.finditer(text or "")]


def _source_text(payload: dict) -> str:
    """The document passage this rule was read from, for the anchor fingerprint.

    Two places are checked because the extraction contract nests the passage one
    level deeper than this function originally looked. Measured across four real
    extraction runs, `formulation.source_text` was present on none of 1,370
    rules and `formulation.canonical.source_text` on all of them — so every
    AI-extracted rule was silently taking the fallback below, and the anchor,
    whose whole purpose is to be the stable axis when wording moves, was being
    computed from model-authored prose that is rewritten on every run.

    It went unnoticed because the mapper happens to seed `description` from the
    same passage today, making the fallback produce the right string for the
    wrong reason. The day a description becomes an actual description, every
    anchor in the system would have changed meaning at once, and the delta would
    have reported a document that had not moved as entirely rewritten.
    """

    formulation = payload.get("formulation")
    if isinstance(formulation, dict):
        canonical = formulation.get("canonical")
        candidates = [
            formulation.get("source_text"),
            canonical.get("source_text") if isinstance(canonical, dict) else None,
        ]
        for text in candidates:
            if isinstance(text, str) and text.strip():
                return text
    # Hand-authored and AI-composed rules carry no document passage. Falling
    # back to the description keeps them comparable to themselves across runs
    # instead of collapsing every one of them onto a single empty anchor.
    description = payload.get("description")
    return description if isinstance(description, str) else ""


def jaccard(left: frozenset[str], right: frozenset[str]) -> float:
    """Overlap of two word sets, 0.0 when either is empty.

    An empty set is treated as matching nothing rather than as matching every
    other empty set: rules without a source passage must not all collapse onto
    each other.
    """
    if not left or not right:
        return 0.0
    return len(left & right) / len(left | right)


@dataclass(frozen=True)
class RuleIdentity:
    """The three fingerprints and the token set used to compare one rule."""

    content_fingerprint: str
    anchor_fingerprint: str
    prose_fingerprint: str
    anchor_tokens: frozenset[str] = field(default_factory=frozenset)


def identify(payload: dict) -> RuleIdentity:
    """Fingerprint a canonical rule payload for cross-run comparison."""
    source = _source_text(payload)
    tokens = _normalise_words(source)
    return RuleIdentity(
        content_fingerprint=canonical_hash(semantic_core(payload)),
        # Hash the *normalised* words, not the raw string, so that a passage
        # differing only in whitespace or casing is recognised as identical.
        anchor_fingerprint=canonical_hash(tokens),
        prose_fingerprint=canonical_hash(
            {"title": payload.get("title", ""), "description": payload.get("description", "")}
        ),
        anchor_tokens=frozenset(tokens),
    )


@dataclass(frozen=True)
class RuleMatch:
    """How one rule of the new run relates to the baseline run."""

    delta_status: DeltaStatus
    #: Key of the baseline rule this one continues, when there is one.
    baseline_key: str | None = None
    #: Semantics identical but the wording was regenerated. Only meaningful when
    #: `delta_status` is `unchanged`.
    reworded: bool = False
    #: Source-passage overlap with the matched baseline rule, 1.0 for an exact
    #: passage match. Shown to reviewers so a borderline match can be judged.
    similarity: float = 0.0


@dataclass(frozen=True)
class DeltaResult:
    """The full comparison of a run against its baseline."""

    matches: dict[str, RuleMatch]
    #: Baseline rules this run did not reproduce.
    removed_keys: list[str]

    @property
    def counts(self) -> dict[str, int]:
        out = {"new": 0, "changed": 0, "unchanged": 0, "baseline": 0}
        for match in self.matches.values():
            out[match.delta_status] += 1
        out["removed"] = len(self.removed_keys)
        out["reworded"] = sum(1 for m in self.matches.values() if m.reworded)
        return out

    @property
    def has_changes(self) -> bool:
        """True when this run produced anything a reviewer needs to look at.

        A removed rule counts: a rule the previous run found and this one did not
        is a change in the document, even though it produces no new row.
        """
        counts = self.counts
        return counts["new"] > 0 or counts["changed"] > 0 or counts["removed"] > 0


def diff_runs(
    new_rules: list[tuple[str, dict]],
    baseline_rules: list[tuple[str, dict]],
) -> DeltaResult:
    """Classify every rule of `new_rules` against `baseline_rules`.

    Both arguments are `(key, payload)` pairs; keys are opaque to this module
    (the caller uses candidate-rule ids) and are simply echoed back in the
    result. Input order is significant only as a deterministic tie-break, so the
    same two runs always compare the same way.

    With no baseline, every rule is `baseline` — the first run of a document
    establishes the reference and is not a delta against anything.
    """
    new_ids = [(key, identify(payload)) for key, payload in new_rules]
    baseline_ids = [(key, identify(payload)) for key, payload in baseline_rules]

    if not baseline_ids:
        return DeltaResult(
            matches={key: RuleMatch(delta_status="baseline") for key, _ in new_ids},
            removed_keys=[],
        )

    matches: dict[str, RuleMatch] = {}
    claimed: set[str] = set()

    # Tier 1 — identical executable semantics *from the same place*. Run to
    # completion before any weaker tier so an exact match is never stolen by a
    # fuzzy one.
    #
    # Semantics alone are not enough. A document can easily contain two clauses
    # that reduce to the same condition and effect, and this platform's whole
    # value is that a rule can be traced to the words it came from. Carrying a
    # reviewer's approval from one clause onto an unrelated clause because the
    # logic happened to coincide would move a citation without anyone deciding
    # to. So the passage must corroborate the match.
    by_content: dict[str, list[tuple[str, RuleIdentity]]] = {}
    for key, identity in baseline_ids:
        by_content.setdefault(identity.content_fingerprint, []).append((key, identity))

    for key, identity in new_ids:
        best: tuple[str, RuleIdentity, float] | None = None
        for base_key, base_identity in by_content.get(identity.content_fingerprint, []):
            if base_key in claimed:
                continue
            score = jaccard(identity.anchor_tokens, base_identity.anchor_tokens)
            # Rules with no document passage at all (hand-authored, AI-composed)
            # have nothing to corroborate with, so semantics stand alone.
            anchorless = not identity.anchor_tokens and not base_identity.anchor_tokens
            if not anchorless and score < SIMILARITY_THRESHOLD:
                continue
            if best is None or score > best[2]:
                best = (base_key, base_identity, score)
        if best is None:
            continue
        base_key, base_identity, score = best
        claimed.add(base_key)
        matches[key] = RuleMatch(
            delta_status="unchanged",
            baseline_key=base_key,
            reworded=identity.prose_fingerprint != base_identity.prose_fingerprint,
            similarity=score,
        )

    # Tier 2 — same source passage, different semantics. The document did not
    # move, so the extractor changed its mind; a reviewer needs to see that.
    by_anchor: dict[str, list[tuple[str, RuleIdentity]]] = {}
    for key, identity in baseline_ids:
        by_anchor.setdefault(identity.anchor_fingerprint, []).append((key, identity))

    for key, identity in new_ids:
        if key in matches or not identity.anchor_tokens:
            continue
        for base_key, _ in by_anchor.get(identity.anchor_fingerprint, []):
            if base_key in claimed:
                continue
            claimed.add(base_key)
            matches[key] = RuleMatch(delta_status="changed", baseline_key=base_key, similarity=1.0)
            break

    # Tier 3 — the passage was revised. Best available match wins; ties break on
    # baseline order so the result never depends on dictionary iteration.
    for key, identity in new_ids:
        if key in matches or not identity.anchor_tokens:
            continue
        best_key: str | None = None
        best_score = 0.0
        for base_key, base_identity in baseline_ids:
            if base_key in claimed:
                continue
            score = jaccard(identity.anchor_tokens, base_identity.anchor_tokens)
            if score > best_score:
                best_key, best_score = base_key, score
        if best_key is not None and best_score >= SIMILARITY_THRESHOLD:
            claimed.add(best_key)
            matches[key] = RuleMatch(delta_status="changed", baseline_key=best_key, similarity=best_score)

    for key, _ in new_ids:
        matches.setdefault(key, RuleMatch(delta_status="new"))

    removed = [key for key, _ in baseline_ids if key not in claimed]
    return DeltaResult(matches=matches, removed_keys=removed)
