"""The sign-in response is checked against the server, not against a mock.

This file exists because of a defect that a full, passing suite did not
catch, and could not have.

`POST /api/auth/login` returned `expires_at` as a float of epoch seconds,
because that is the type a JWT's `exp` claim needs and the minting function
hands it straight back. The browser client declared `expires_at: string` and
rejected any session whose expiry was not a string. So a correct sign-in
stored a session, the very next read discarded it, and the interface came up
looking signed in while sending no credentials at all -- falling back to a
role left in local storage by an earlier build. Every request still returned
200, because an unauthenticated caller resolves to the least privilege and
the pages it loads are readable by anyone.

Nothing failed. That is the point.

The web test covering sign-in mocked the endpoint and wrote the mock from the
intended contract -- an ISO string -- so it asserted the shape the author
wanted rather than the shape the server sent. A mock is a statement of belief
about a boundary; it cannot detect that the belief is wrong. `api.ts` already
carries a comment about this exact failure happening once before, with three
fields the server never sent.

So these tests call the real application. They are deliberately about the
*wire*: the field's type and parseability, not the behaviour behind it.
"""
from __future__ import annotations

import datetime as dt
import json
import os
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

ACCOUNTS = """
# generated by the test
wireuser:wire-password-1234:policy_author
"""


@pytest.fixture()
def client(tmp_path: Path):
    """A real app with local accounts enabled, on a throwaway account file."""

    accounts = tmp_path / "accounts.txt"
    accounts.write_text(ACCOUNTS, encoding="utf-8")

    previous = {
        key: os.environ.get(key)
        for key in (
            "RBAC_ENABLED",
            "LOCAL_ACCOUNTS_ENABLED",
            "LOCAL_ACCOUNTS_FILE",
            "LOCAL_SIGNING_KEY_FILE",
            "ENVIRONMENT",
        )
    }
    os.environ.update(
        {
            "RBAC_ENABLED": "true",
            "LOCAL_ACCOUNTS_ENABLED": "true",
            "LOCAL_ACCOUNTS_FILE": str(accounts),
            "LOCAL_SIGNING_KEY_FILE": str(tmp_path / "signing-key.pem"),
            "ENVIRONMENT": "development",
        }
    )

    from policy_platform.api.app import create_app
    from policy_platform.infrastructure.settings import get_settings

    get_settings.cache_clear()
    with TestClient(create_app(), raise_server_exceptions=False) as c:
        yield c

    for key, value in previous.items():
        if value is None:
            os.environ.pop(key, None)
        else:
            os.environ[key] = value
    get_settings.cache_clear()


def _login(client) -> dict:
    response = client.post(
        "/api/auth/login",
        json={"username": "wireuser", "password": "wire-password-1234"},
    )
    assert response.status_code == 200, response.text
    return response.json()


def test_the_expiry_is_a_string_on_the_wire(client) -> None:
    """The field's *type*, asserted against the server that produces it.

    A number here is not a cosmetic difference. It is the difference between a
    session the client keeps and one it silently throws away.
    """

    body = _login(client)
    expires_at = body["expires_at"]

    assert isinstance(expires_at, str), (
        f"expires_at is {type(expires_at).__name__} ({expires_at!r}). The client "
        "declares it a string and discards any session whose expiry is not one, "
        "which signs the user out without telling them."
    )


def test_the_expiry_parses_as_an_instant_in_the_future(client) -> None:
    """Parseable, timezone-aware, and actually ahead of now.

    A string that does not parse fails the same way a number does, and a naive
    timestamp is worse: it parses, then compares wrongly by whatever the
    reader's offset happens to be, so the bug only appears in some timezones.
    """

    body = _login(client)
    parsed = dt.datetime.fromisoformat(body["expires_at"])

    assert parsed.tzinfo is not None, (
        f"{body['expires_at']!r} carries no timezone, so any comparison against "
        "'now' depends on where the reader is sitting"
    )
    assert parsed > dt.datetime.now(dt.timezone.utc), "the session expires in the past"


def test_the_expiry_matches_how_every_other_timestamp_is_sent(client) -> None:
    """One representation for one concept, across the whole API.

    Checked against the app's own OpenAPI description rather than a list
    written here, so this keeps holding as the surface grows.
    """

    from policy_platform.api.app import create_app

    schemas = create_app().openapi().get("components", {}).get("schemas", {})
    formats = {
        spec.get("format")
        for body in schemas.values()
        for name, spec in (body.get("properties") or {}).items()
        if name.endswith("_at") and spec.get("type") == "string"
    }

    assert "date-time" in formats, (
        "no other timestamp in this API is a date-time string, so the premise "
        "of this test no longer holds and it should be revisited rather than "
        "deleted"
    )

    body = _login(client)
    dt.datetime.fromisoformat(body["expires_at"])  # raises if it is not one


def test_the_response_carries_exactly_the_fields_the_client_reads(client) -> None:
    """The client builds its session from four fields. All four must arrive.

    Named individually rather than by set equality: a server that adds a field
    breaks nobody, while a server that drops one breaks sign-in, and only the
    second should fail here.
    """

    body = _login(client)

    for field in ("access_token", "token_type", "expires_at", "role", "name"):
        assert field in body, f"the client reads {field!r} and the server did not send it"

    assert body["token_type"] == "bearer"
    assert isinstance(body["access_token"], str) and body["access_token"]
    assert body["role"] == "policy_author"
    assert body["name"] == "wireuser"


def test_a_refused_sign_in_says_nothing_about_which_half_was_wrong(client) -> None:
    """Kept here because it is also a property of the wire, not of the screen."""

    unknown = client.post(
        "/api/auth/login", json={"username": "nobody", "password": "wire-password-1234"}
    )
    wrong = client.post(
        "/api/auth/login", json={"username": "wireuser", "password": "not-the-password"}
    )

    assert unknown.status_code == 401
    assert wrong.status_code == 401
    assert json.dumps(unknown.json()) == json.dumps(wrong.json()), (
        "the two refusals differ, so the response says whether the username "
        "exists"
    )
